// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/service.go -destination=internal/service/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "userservice/internal/model"
	service "userservice/internal/service"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetTelegramAccount mocks base method.
func (m *MockUserRepository) GetTelegramAccount(ctx context.Context, userId uuid.UUID) (*model.TelegramAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTelegramAccount", ctx, userId)
	ret0, _ := ret[0].(*model.TelegramAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTelegramAccount indicates an expected call of GetTelegramAccount.
func (mr *MockUserRepositoryMockRecorder) GetTelegramAccount(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTelegramAccount", reflect.TypeOf((*MockUserRepository)(nil).GetTelegramAccount), ctx, userId)
}

// GetTelegramAccountByTelegramId mocks base method.
func (m *MockUserRepository) GetTelegramAccountByTelegramId(ctx context.Context, telegramId int64) (*model.TelegramAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTelegramAccountByTelegramId", ctx, telegramId)
	ret0, _ := ret[0].(*model.TelegramAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTelegramAccountByTelegramId indicates an expected call of GetTelegramAccountByTelegramId.
func (mr *MockUserRepositoryMockRecorder) GetTelegramAccountByTelegramId(ctx, telegramId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTelegramAccountByTelegramId", reflect.TypeOf((*MockUserRepository)(nil).GetTelegramAccountByTelegramId), ctx, telegramId)
}

// GetTutorProfile mocks base method.
func (m *MockUserRepository) GetTutorProfile(ctx context.Context, userId uuid.UUID) (*model.TutorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTutorProfile", ctx, userId)
	ret0, _ := ret[0].(*model.TutorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTutorProfile indicates an expected call of GetTutorProfile.
func (mr *MockUserRepositoryMockRecorder) GetTutorProfile(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTutorProfile", reflect.TypeOf((*MockUserRepository)(nil).GetTutorProfile), ctx, userId)
}

// GetUser mocks base method.
func (m *MockUserRepository) GetUser(ctx context.Context, id uuid.UUID) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserRepositoryMockRecorder) GetUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserRepository)(nil).GetUser), ctx, id)
}

// NewUserCreationRepositoryTx mocks base method.
func (m *MockUserRepository) NewUserCreationRepositoryTx(ctx context.Context) (service.UserCreationRepositoryTx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUserCreationRepositoryTx", ctx)
	ret0, _ := ret[0].(service.UserCreationRepositoryTx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewUserCreationRepositoryTx indicates an expected call of NewUserCreationRepositoryTx.
func (mr *MockUserRepositoryMockRecorder) NewUserCreationRepositoryTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUserCreationRepositoryTx", reflect.TypeOf((*MockUserRepository)(nil).NewUserCreationRepositoryTx), ctx)
}

// UpdateTutorProfile mocks base method.
func (m *MockUserRepository) UpdateTutorProfile(ctx context.Context, userId uuid.UUID, input *model.UpdateTutorProfileInput) (*model.TutorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTutorProfile", ctx, userId, input)
	ret0, _ := ret[0].(*model.TutorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTutorProfile indicates an expected call of UpdateTutorProfile.
func (mr *MockUserRepositoryMockRecorder) UpdateTutorProfile(ctx, userId, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTutorProfile", reflect.TypeOf((*MockUserRepository)(nil).UpdateTutorProfile), ctx, userId, input)
}

// UpdateUser mocks base method.
func (m *MockUserRepository) UpdateUser(ctx context.Context, id uuid.UUID, input *model.UpdateUserInput) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, id, input)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserRepositoryMockRecorder) UpdateUser(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserRepository)(nil).UpdateUser), ctx, id, input)
}

// MockUserCreationRepositoryTx is a mock of UserCreationRepositoryTx interface.
type MockUserCreationRepositoryTx struct {
	ctrl     *gomock.Controller
	recorder *MockUserCreationRepositoryTxMockRecorder
	isgomock struct{}
}

// MockUserCreationRepositoryTxMockRecorder is the mock recorder for MockUserCreationRepositoryTx.
type MockUserCreationRepositoryTxMockRecorder struct {
	mock *MockUserCreationRepositoryTx
}

// NewMockUserCreationRepositoryTx creates a new mock instance.
func NewMockUserCreationRepositoryTx(ctrl *gomock.Controller) *MockUserCreationRepositoryTx {
	mock := &MockUserCreationRepositoryTx{ctrl: ctrl}
	mock.recorder = &MockUserCreationRepositoryTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCreationRepositoryTx) EXPECT() *MockUserCreationRepositoryTxMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockUserCreationRepositoryTx) Commit(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockUserCreationRepositoryTxMockRecorder) Commit(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockUserCreationRepositoryTx)(nil).Commit), ctx)
}

// CreateTelegramAccount mocks base method.
func (m *MockUserCreationRepositoryTx) CreateTelegramAccount(ctx context.Context, input *model.RepositoryCreateTelegramAccountInput) (*model.TelegramAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTelegramAccount", ctx, input)
	ret0, _ := ret[0].(*model.TelegramAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTelegramAccount indicates an expected call of CreateTelegramAccount.
func (mr *MockUserCreationRepositoryTxMockRecorder) CreateTelegramAccount(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTelegramAccount", reflect.TypeOf((*MockUserCreationRepositoryTx)(nil).CreateTelegramAccount), ctx, input)
}

// CreateTutorProfile mocks base method.
func (m *MockUserCreationRepositoryTx) CreateTutorProfile(ctx context.Context, input *model.RepositoryCreateTutorProfileInput) (*model.TutorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTutorProfile", ctx, input)
	ret0, _ := ret[0].(*model.TutorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTutorProfile indicates an expected call of CreateTutorProfile.
func (mr *MockUserCreationRepositoryTxMockRecorder) CreateTutorProfile(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTutorProfile", reflect.TypeOf((*MockUserCreationRepositoryTx)(nil).CreateTutorProfile), ctx, input)
}

// CreateUser mocks base method.
func (m *MockUserCreationRepositoryTx) CreateUser(ctx context.Context, input *model.RepositoryCreateUserInput) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, input)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserCreationRepositoryTxMockRecorder) CreateUser(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserCreationRepositoryTx)(nil).CreateUser), ctx, input)
}

// Rollback mocks base method.
func (m *MockUserCreationRepositoryTx) Rollback(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockUserCreationRepositoryTxMockRecorder) Rollback(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockUserCreationRepositoryTx)(nil).Rollback), ctx)
}

// MockTutorStudentsRepository is a mock of TutorStudentsRepository interface.
type MockTutorStudentsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTutorStudentsRepositoryMockRecorder
	isgomock struct{}
}

// MockTutorStudentsRepositoryMockRecorder is the mock recorder for MockTutorStudentsRepository.
type MockTutorStudentsRepositoryMockRecorder struct {
	mock *MockTutorStudentsRepository
}

// NewMockTutorStudentsRepository creates a new mock instance.
func NewMockTutorStudentsRepository(ctrl *gomock.Controller) *MockTutorStudentsRepository {
	mock := &MockTutorStudentsRepository{ctrl: ctrl}
	mock.recorder = &MockTutorStudentsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTutorStudentsRepository) EXPECT() *MockTutorStudentsRepositoryMockRecorder {
	return m.recorder
}

// CreateTutorStudent mocks base method.
func (m *MockTutorStudentsRepository) CreateTutorStudent(ctx context.Context, input *model.RepositoryCreateTutorStudentInput) (*model.TutorStudent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTutorStudent", ctx, input)
	ret0, _ := ret[0].(*model.TutorStudent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTutorStudent indicates an expected call of CreateTutorStudent.
func (mr *MockTutorStudentsRepositoryMockRecorder) CreateTutorStudent(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTutorStudent", reflect.TypeOf((*MockTutorStudentsRepository)(nil).CreateTutorStudent), ctx, input)
}

// DeleteTutorStudent mocks base method.
func (m *MockTutorStudentsRepository) DeleteTutorStudent(ctx context.Context, tutorId, studentId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTutorStudent", ctx, tutorId, studentId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTutorStudent indicates an expected call of DeleteTutorStudent.
func (mr *MockTutorStudentsRepositoryMockRecorder) DeleteTutorStudent(ctx, tutorId, studentId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTutorStudent", reflect.TypeOf((*MockTutorStudentsRepository)(nil).DeleteTutorStudent), ctx, tutorId, studentId)
}

// GetTutorStudent mocks base method.
func (m *MockTutorStudentsRepository) GetTutorStudent(ctx context.Context, tutorId, studentId uuid.UUID) (*model.TutorStudent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTutorStudent", ctx, tutorId, studentId)
	ret0, _ := ret[0].(*model.TutorStudent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTutorStudent indicates an expected call of GetTutorStudent.
func (mr *MockTutorStudentsRepositoryMockRecorder) GetTutorStudent(ctx, tutorId, studentId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTutorStudent", reflect.TypeOf((*MockTutorStudentsRepository)(nil).GetTutorStudent), ctx, tutorId, studentId)
}

// ListTutorStudents mocks base method.
func (m *MockTutorStudentsRepository) ListTutorStudents(ctx context.Context, tutorId, studentId uuid.UUID) ([]*model.TutorStudent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTutorStudents", ctx, tutorId, studentId)
	ret0, _ := ret[0].([]*model.TutorStudent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTutorStudents indicates an expected call of ListTutorStudents.
func (mr *MockTutorStudentsRepositoryMockRecorder) ListTutorStudents(ctx, tutorId, studentId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTutorStudents", reflect.TypeOf((*MockTutorStudentsRepository)(nil).ListTutorStudents), ctx, tutorId, studentId)
}

// UpdateTutorStudent mocks base method.
func (m *MockTutorStudentsRepository) UpdateTutorStudent(ctx context.Context, tutorId, studentId uuid.UUID, input *model.UpdateTutorStudentInput) (*model.TutorStudent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTutorStudent", ctx, tutorId, studentId, input)
	ret0, _ := ret[0].(*model.TutorStudent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTutorStudent indicates an expected call of UpdateTutorStudent.
func (mr *MockTutorStudentsRepositoryMockRecorder) UpdateTutorStudent(ctx, tutorId, studentId, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTutorStudent", reflect.TypeOf((*MockTutorStudentsRepository)(nil).UpdateTutorStudent), ctx, tutorId, studentId, input)
}
