// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: payment_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPaymentInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      *string                `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3,oneof" json:"lesson_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentInfoRequest) Reset() {
	*x = GetPaymentInfoRequest{}
	mi := &file_payment_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentInfoRequest) ProtoMessage() {}

func (x *GetPaymentInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentInfoRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetPaymentInfoRequest) GetLessonId() string {
	if x != nil && x.LessonId != nil {
		return *x.LessonId
	}
	return ""
}

type SubmitPaymentReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      *string                `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3,oneof" json:"lesson_id,omitempty"`
	FileId        *string                `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3,oneof" json:"file_id,omitempty"` // чек (file_service.files.id)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPaymentReceiptRequest) Reset() {
	*x = SubmitPaymentReceiptRequest{}
	mi := &file_payment_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPaymentReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPaymentReceiptRequest) ProtoMessage() {}

func (x *SubmitPaymentReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPaymentReceiptRequest.ProtoReflect.Descriptor instead.
func (*SubmitPaymentReceiptRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitPaymentReceiptRequest) GetLessonId() string {
	if x != nil && x.LessonId != nil {
		return *x.LessonId
	}
	return ""
}

func (x *SubmitPaymentReceiptRequest) GetFileId() string {
	if x != nil && x.FileId != nil {
		return *x.FileId
	}
	return ""
}

type GetReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiptId     string                 `protobuf:"bytes,1,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReceiptRequest) Reset() {
	*x = GetReceiptRequest{}
	mi := &file_payment_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptRequest) ProtoMessage() {}

func (x *GetReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptRequest.ProtoReflect.Descriptor instead.
func (*GetReceiptRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetReceiptRequest) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

type VerifyReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiptId     string                 `protobuf:"bytes,1,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyReceiptRequest) Reset() {
	*x = VerifyReceiptRequest{}
	mi := &file_payment_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyReceiptRequest) ProtoMessage() {}

func (x *VerifyReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyReceiptRequest.ProtoReflect.Descriptor instead.
func (*VerifyReceiptRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyReceiptRequest) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

type GetReceiptFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiptId     string                 `protobuf:"bytes,1,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReceiptFileRequest) Reset() {
	*x = GetReceiptFileRequest{}
	mi := &file_payment_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptFileRequest) ProtoMessage() {}

func (x *GetReceiptFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptFileRequest.ProtoReflect.Descriptor instead.
func (*GetReceiptFileRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetReceiptFileRequest) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

// Exactly one of tutor_id or student_id must be set.
type ListReceiptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TutorId       *string                `protobuf:"bytes,1,opt,name=tutor_id,json=tutorId,proto3,oneof" json:"tutor_id,omitempty"`
	StudentId     *string                `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3,oneof" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReceiptsRequest) Reset() {
	*x = ListReceiptsRequest{}
	mi := &file_payment_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReceiptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReceiptsRequest) ProtoMessage() {}

func (x *ListReceiptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReceiptsRequest.ProtoReflect.Descriptor instead.
func (*ListReceiptsRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListReceiptsRequest) GetTutorId() string {
	if x != nil && x.TutorId != nil {
		return *x.TutorId
	}
	return ""
}

func (x *ListReceiptsRequest) GetStudentId() string {
	if x != nil && x.StudentId != nil {
		return *x.StudentId
	}
	return ""
}

type GetTutorAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TutorId       string                 `protobuf:"bytes,1,opt,name=tutor_id,json=tutorId,proto3" json:"tutor_id,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3,oneof" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3,oneof" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTutorAnalyticsRequest) Reset() {
	*x = GetTutorAnalyticsRequest{}
	mi := &file_payment_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTutorAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTutorAnalyticsRequest) ProtoMessage() {}

func (x *GetTutorAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTutorAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetTutorAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetTutorAnalyticsRequest) GetTutorId() string {
	if x != nil {
		return x.TutorId
	}
	return ""
}

func (x *GetTutorAnalyticsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetTutorAnalyticsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type PaymentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      *string                `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3,oneof" json:"lesson_id,omitempty"`
	PriceRub      *int32                 `protobuf:"varint,2,opt,name=price_rub,json=priceRub,proto3,oneof" json:"price_rub,omitempty"`
	PaymentInfo   *string                `protobuf:"bytes,3,opt,name=payment_info,json=paymentInfo,proto3,oneof" json:"payment_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentInfo) Reset() {
	*x = PaymentInfo{}
	mi := &file_payment_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentInfo) ProtoMessage() {}

func (x *PaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentInfo.ProtoReflect.Descriptor instead.
func (*PaymentInfo) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentInfo) GetLessonId() string {
	if x != nil && x.LessonId != nil {
		return *x.LessonId
	}
	return ""
}

func (x *PaymentInfo) GetPriceRub() int32 {
	if x != nil && x.PriceRub != nil {
		return *x.PriceRub
	}
	return 0
}

func (x *PaymentInfo) GetPaymentInfo() string {
	if x != nil && x.PaymentInfo != nil {
		return *x.PaymentInfo
	}
	return ""
}

type Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // UUIDv7
	LessonId      *string                `protobuf:"bytes,2,opt,name=lesson_id,json=lessonId,proto3,oneof" json:"lesson_id,omitempty"` // Refers to schedule.lessons.id
	FileId        *string                `protobuf:"bytes,3,opt,name=file_id,json=fileId,proto3,oneof" json:"file_id,omitempty"`       // Refers to file_service.files.id
	IsVerified    bool                   `protobuf:"varint,4,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EditedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=edited_at,json=editedAt,proto3" json:"edited_at,omitempty"`
	PriceRub      *int32                 `protobuf:"varint,7,opt,name=price_rub,json=priceRub,proto3,oneof" json:"price_rub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_payment_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{8}
}

func (x *Receipt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Receipt) GetLessonId() string {
	if x != nil && x.LessonId != nil {
		return *x.LessonId
	}
	return ""
}

func (x *Receipt) GetFileId() string {
	if x != nil && x.FileId != nil {
		return *x.FileId
	}
	return ""
}

func (x *Receipt) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *Receipt) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Receipt) GetEditedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EditedAt
	}
	return nil
}

func (x *Receipt) GetPriceRub() int32 {
	if x != nil && x.PriceRub != nil {
		return *x.PriceRub
	}
	return 0
}

type ReceiptFileURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *string                `protobuf:"bytes,1,opt,name=url,proto3,oneof" json:"url,omitempty"` // временная ссылка на файл из file-service
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiptFileURL) Reset() {
	*x = ReceiptFileURL{}
	mi := &file_payment_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptFileURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptFileURL) ProtoMessage() {}

func (x *ReceiptFileURL) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptFileURL.ProtoReflect.Descriptor instead.
func (*ReceiptFileURL) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{9}
}

func (x *ReceiptFileURL) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type ListReceiptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipts      []*Receipt             `protobuf:"bytes,1,rep,name=receipts,proto3" json:"receipts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReceiptsResponse) Reset() {
	*x = ListReceiptsResponse{}
	mi := &file_payment_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReceiptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReceiptsResponse) ProtoMessage() {}

func (x *ListReceiptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReceiptsResponse.ProtoReflect.Descriptor instead.
func (*ListReceiptsResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListReceiptsResponse) GetReceipts() []*Receipt {
	if x != nil {
		return x.Receipts
	}
	return nil
}

type TutorAnalytics struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TutorId               string                 `protobuf:"bytes,1,opt,name=tutor_id,json=tutorId,proto3" json:"tutor_id,omitempty"`
	From                  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3,oneof" json:"from,omitempty"`
	To                    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3,oneof" json:"to,omitempty"`
	TotalRevenueRub       int64                  `protobuf:"varint,4,opt,name=total_revenue_rub,json=totalRevenueRub,proto3" json:"total_revenue_rub,omitempty"`
	CompletedLessonsCount int64                  `protobuf:"varint,5,opt,name=completed_lessons_count,json=completedLessonsCount,proto3" json:"completed_lessons_count,omitempty"`
	CancelledLessonsCount int64                  `protobuf:"varint,6,opt,name=cancelled_lessons_count,json=cancelledLessonsCount,proto3" json:"cancelled_lessons_count,omitempty"`
	ActiveStudentsCount   int64                  `protobuf:"varint,7,opt,name=active_students_count,json=activeStudentsCount,proto3" json:"active_students_count,omitempty"`
	UnpaidLessonsCount    int64                  `protobuf:"varint,8,opt,name=unpaid_lessons_count,json=unpaidLessonsCount,proto3" json:"unpaid_lessons_count,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TutorAnalytics) Reset() {
	*x = TutorAnalytics{}
	mi := &file_payment_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TutorAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TutorAnalytics) ProtoMessage() {}

func (x *TutorAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TutorAnalytics.ProtoReflect.Descriptor instead.
func (*TutorAnalytics) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{11}
}

func (x *TutorAnalytics) GetTutorId() string {
	if x != nil {
		return x.TutorId
	}
	return ""
}

func (x *TutorAnalytics) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *TutorAnalytics) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *TutorAnalytics) GetTotalRevenueRub() int64 {
	if x != nil {
		return x.TotalRevenueRub
	}
	return 0
}

func (x *TutorAnalytics) GetCompletedLessonsCount() int64 {
	if x != nil {
		return x.CompletedLessonsCount
	}
	return 0
}

func (x *TutorAnalytics) GetCancelledLessonsCount() int64 {
	if x != nil {
		return x.CancelledLessonsCount
	}
	return 0
}

func (x *TutorAnalytics) GetActiveStudentsCount() int64 {
	if x != nil {
		return x.ActiveStudentsCount
	}
	return 0
}

func (x *TutorAnalytics) GetUnpaidLessonsCount() int64 {
	if x != nil {
		return x.UnpaidLessonsCount
	}
	return 0
}

var File_payment_service_proto protoreflect.FileDescriptor

const file_payment_service_proto_rawDesc = "" +
	"\n" +
	"\x15payment_service.proto\x12\n" +
	"payment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"G\n" +
	"\x15GetPaymentInfoRequest\x12 \n" +
	"\tlesson_id\x18\x01 \x01(\tH\x00R\blessonId\x88\x01\x01B\f\n" +
	"\n" +
	"_lesson_id\"w\n" +
	"\x1bSubmitPaymentReceiptRequest\x12 \n" +
	"\tlesson_id\x18\x01 \x01(\tH\x00R\blessonId\x88\x01\x01\x12\x1c\n" +
	"\afile_id\x18\x02 \x01(\tH\x01R\x06fileId\x88\x01\x01B\f\n" +
	"\n" +
	"_lesson_idB\n" +
	"\n" +
	"\b_file_id\"2\n" +
	"\x11GetReceiptRequest\x12\x1d\n" +
	"\n" +
	"receipt_id\x18\x01 \x01(\tR\treceiptId\"5\n" +
	"\x14VerifyReceiptRequest\x12\x1d\n" +
	"\n" +
	"receipt_id\x18\x01 \x01(\tR\treceiptId\"6\n" +
	"\x15GetReceiptFileRequest\x12\x1d\n" +
	"\n" +
	"receipt_id\x18\x01 \x01(\tR\treceiptId\"u\n" +
	"\x13ListReceiptsRequest\x12\x1e\n" +
	"\btutor_id\x18\x01 \x01(\tH\x00R\atutorId\x88\x01\x01\x12\"\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tH\x01R\tstudentId\x88\x01\x01B\v\n" +
	"\t_tutor_idB\r\n" +
	"\v_student_id\"\xab\x01\n" +
	"\x18GetTutorAnalyticsRequest\x12\x19\n" +
	"\btutor_id\x18\x01 \x01(\tR\atutorId\x123\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04from\x88\x01\x01\x12/\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x02to\x88\x01\x01B\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_to\"\xa6\x01\n" +
	"\vPaymentInfo\x12 \n" +
	"\tlesson_id\x18\x01 \x01(\tH\x00R\blessonId\x88\x01\x01\x12 \n" +
	"\tprice_rub\x18\x02 \x01(\x05H\x01R\bpriceRub\x88\x01\x01\x12&\n" +
	"\fpayment_info\x18\x03 \x01(\tH\x02R\vpaymentInfo\x88\x01\x01B\f\n" +
	"\n" +
	"_lesson_idB\f\n" +
	"\n" +
	"_price_rubB\x0f\n" +
	"\r_payment_info\"\xb8\x02\n" +
	"\aReceipt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\tlesson_id\x18\x02 \x01(\tH\x00R\blessonId\x88\x01\x01\x12\x1c\n" +
	"\afile_id\x18\x03 \x01(\tH\x01R\x06fileId\x88\x01\x01\x12\x1f\n" +
	"\vis_verified\x18\x04 \x01(\bR\n" +
	"isVerified\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tedited_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\beditedAt\x12 \n" +
	"\tprice_rub\x18\a \x01(\x05H\x02R\bpriceRub\x88\x01\x01B\f\n" +
	"\n" +
	"_lesson_idB\n" +
	"\n" +
	"\b_file_idB\f\n" +
	"\n" +
	"_price_rub\"/\n" +
	"\x0eReceiptFileURL\x12\x15\n" +
	"\x03url\x18\x01 \x01(\tH\x00R\x03url\x88\x01\x01B\x06\n" +
	"\x04_url\"G\n" +
	"\x14ListReceiptsResponse\x12/\n" +
	"\breceipts\x18\x01 \x03(\v2\x13.payment.v1.ReceiptR\breceipts\"\xa3\x03\n" +
	"\x0eTutorAnalytics\x12\x19\n" +
	"\btutor_id\x18\x01 \x01(\tR\atutorId\x123\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04from\x88\x01\x01\x12/\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x02to\x88\x01\x01\x12*\n" +
	"\x11total_revenue_rub\x18\x04 \x01(\x03R\x0ftotalRevenueRub\x126\n" +
	"\x17completed_lessons_count\x18\x05 \x01(\x03R\x15completedLessonsCount\x126\n" +
	"\x17cancelled_lessons_count\x18\x06 \x01(\x03R\x15cancelledLessonsCount\x122\n" +
	"\x15active_students_count\x18\a \x01(\x03R\x13activeStudentsCount\x120\n" +
	"\x14unpaid_lessons_count\x18\b \x01(\x03R\x12unpaidLessonsCountB\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_to2\xb9\x04\n" +
	"\x0ePaymentService\x12L\n" +
	"\x0eGetPaymentInfo\x12!.payment.v1.GetPaymentInfoRequest\x1a\x17.payment.v1.PaymentInfo\x12T\n" +
	"\x14SubmitPaymentReceipt\x12'.payment.v1.SubmitPaymentReceiptRequest\x1a\x13.payment.v1.Receipt\x12@\n" +
	"\n" +
	"GetReceipt\x12\x1d.payment.v1.GetReceiptRequest\x1a\x13.payment.v1.Receipt\x12F\n" +
	"\rVerifyReceipt\x12 .payment.v1.VerifyReceiptRequest\x1a\x13.payment.v1.Receipt\x12O\n" +
	"\x0eGetReceiptFile\x12!.payment.v1.GetReceiptFileRequest\x1a\x1a.payment.v1.ReceiptFileURL\x12Q\n" +
	"\fListReceipts\x12\x1f.payment.v1.ListReceiptsRequest\x1a .payment.v1.ListReceiptsResponse\x12U\n" +
	"\x11GetTutorAnalytics\x12$.payment.v1.GetTutorAnalyticsRequest\x1a\x1a.payment.v1.TutorAnalyticsB\x17Z\x15payment_service/protob\x06proto3"

var (
	file_payment_service_proto_rawDescOnce sync.Once
	file_payment_service_proto_rawDescData []byte
)

func file_payment_service_proto_rawDescGZIP() []byte {
	file_payment_service_proto_rawDescOnce.Do(func() {
		file_payment_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_service_proto_rawDesc), len(file_payment_service_proto_rawDesc)))
	})
	return file_payment_service_proto_rawDescData
}

var file_payment_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_payment_service_proto_goTypes = []any{
	(*GetPaymentInfoRequest)(nil),       // 0: payment.v1.GetPaymentInfoRequest
	(*SubmitPaymentReceiptRequest)(nil), // 1: payment.v1.SubmitPaymentReceiptRequest
	(*GetReceiptRequest)(nil),           // 2: payment.v1.GetReceiptRequest
	(*VerifyReceiptRequest)(nil),        // 3: payment.v1.VerifyReceiptRequest
	(*GetReceiptFileRequest)(nil),       // 4: payment.v1.GetReceiptFileRequest
	(*ListReceiptsRequest)(nil),         // 5: payment.v1.ListReceiptsRequest
	(*GetTutorAnalyticsRequest)(nil),    // 6: payment.v1.GetTutorAnalyticsRequest
	(*PaymentInfo)(nil),                 // 7: payment.v1.PaymentInfo
	(*Receipt)(nil),                     // 8: payment.v1.Receipt
	(*ReceiptFileURL)(nil),              // 9: payment.v1.ReceiptFileURL
	(*ListReceiptsResponse)(nil),        // 10: payment.v1.ListReceiptsResponse
	(*TutorAnalytics)(nil),              // 11: payment.v1.TutorAnalytics
	(*timestamppb.Timestamp)(nil),       // 12: google.protobuf.Timestamp
}
var file_payment_service_proto_depIdxs = []int32{
	12, // 0: payment.v1.GetTutorAnalyticsRequest.from:type_name -> google.protobuf.Timestamp
	12, // 1: payment.v1.GetTutorAnalyticsRequest.to:type_name -> google.protobuf.Timestamp
	12, // 2: payment.v1.Receipt.created_at:type_name -> google.protobuf.Timestamp
	12, // 3: payment.v1.Receipt.edited_at:type_name -> google.protobuf.Timestamp
	8,  // 4: payment.v1.ListReceiptsResponse.receipts:type_name -> payment.v1.Receipt
	12, // 5: payment.v1.TutorAnalytics.from:type_name -> google.protobuf.Timestamp
	12, // 6: payment.v1.TutorAnalytics.to:type_name -> google.protobuf.Timestamp
	0,  // 7: payment.v1.PaymentService.GetPaymentInfo:input_type -> payment.v1.GetPaymentInfoRequest
	1,  // 8: payment.v1.PaymentService.SubmitPaymentReceipt:input_type -> payment.v1.SubmitPaymentReceiptRequest
	2,  // 9: payment.v1.PaymentService.GetReceipt:input_type -> payment.v1.GetReceiptRequest
	3,  // 10: payment.v1.PaymentService.VerifyReceipt:input_type -> payment.v1.VerifyReceiptRequest
	4,  // 11: payment.v1.PaymentService.GetReceiptFile:input_type -> payment.v1.GetReceiptFileRequest
	5,  // 12: payment.v1.PaymentService.ListReceipts:input_type -> payment.v1.ListReceiptsRequest
	6,  // 13: payment.v1.PaymentService.GetTutorAnalytics:input_type -> payment.v1.GetTutorAnalyticsRequest
	7,  // 14: payment.v1.PaymentService.GetPaymentInfo:output_type -> payment.v1.PaymentInfo
	8,  // 15: payment.v1.PaymentService.SubmitPaymentReceipt:output_type -> payment.v1.Receipt
	8,  // 16: payment.v1.PaymentService.GetReceipt:output_type -> payment.v1.Receipt
	8,  // 17: payment.v1.PaymentService.VerifyReceipt:output_type -> payment.v1.Receipt
	9,  // 18: payment.v1.PaymentService.GetReceiptFile:output_type -> payment.v1.ReceiptFileURL
	10, // 19: payment.v1.PaymentService.ListReceipts:output_type -> payment.v1.ListReceiptsResponse
	11, // 20: payment.v1.PaymentService.GetTutorAnalytics:output_type -> payment.v1.TutorAnalytics
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_payment_service_proto_init() }
func file_payment_service_proto_init() {
	if File_payment_service_proto != nil {
		return
	}
	file_payment_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_payment_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_payment_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_payment_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_payment_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_payment_service_proto_msgTypes[8].OneofWrappers = []any{}
	file_payment_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_payment_service_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_service_proto_rawDesc), len(file_payment_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_service_proto_goTypes,
		DependencyIndexes: file_payment_service_proto_depIdxs,
		MessageInfos:      file_payment_service_proto_msgTypes,
	}.Build()
	File_payment_service_proto = out.File
	file_payment_service_proto_goTypes = nil
	file_payment_service_proto_depIdxs = nil
}
