// Code generated by protoc-gen-go. DO NOT EDIT.
// source: audit_service.proto

package api

import (
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// RecordEventRequest is the proto message for recording an audit event.
type RecordEventRequest struct {
	UserId       string
	Action       string
	ResourceType string
	ResourceId   *string
	Details      *string
	IpAddress    *string
}

func (m *RecordEventRequest) Reset()        { *m = RecordEventRequest{} }
func (m *RecordEventRequest) String() string { return "RecordEventRequest" }
func (m *RecordEventRequest) ProtoMessage()  {}

// RecordEventResponse is the proto message for a record event response.
type RecordEventResponse struct {
	Id string
}

func (m *RecordEventResponse) Reset()        { *m = RecordEventResponse{} }
func (m *RecordEventResponse) String() string { return "RecordEventResponse" }
func (m *RecordEventResponse) ProtoMessage()  {}

// ListEventsRequest is the proto message for listing audit events.
type ListEventsRequest struct {
	UserId       *string
	ResourceType *string
	ResourceId   *string
	Page         *int32
	PageSize     *int32
}

func (m *ListEventsRequest) Reset()        { *m = ListEventsRequest{} }
func (m *ListEventsRequest) String() string { return "ListEventsRequest" }
func (m *ListEventsRequest) ProtoMessage()  {}

// GetUserId returns the user_id value or empty string if nil.
func (m *ListEventsRequest) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

// GetResourceType returns the resource_type value or empty string if nil.
func (m *ListEventsRequest) GetResourceType() string {
	if m != nil && m.ResourceType != nil {
		return *m.ResourceType
	}
	return ""
}

// GetResourceId returns the resource_id value or empty string if nil.
func (m *ListEventsRequest) GetResourceId() string {
	if m != nil && m.ResourceId != nil {
		return *m.ResourceId
	}
	return ""
}

// AuditEvent is the proto message for a single audit log entry.
type AuditEvent struct {
	Id           string
	UserId       string
	Action       string
	ResourceType string
	ResourceId   *string
	Details      *string
	IpAddress    *string
	CreatedAt    *timestamppb.Timestamp
}

func (m *AuditEvent) Reset()        { *m = AuditEvent{} }
func (m *AuditEvent) String() string { return "AuditEvent" }
func (m *AuditEvent) ProtoMessage()  {}

// ListEventsResponse is the proto message for the list events response.
type ListEventsResponse struct {
	Events     []*AuditEvent
	Page       int32
	TotalCount int64
}

func (m *ListEventsResponse) Reset()        { *m = ListEventsResponse{} }
func (m *ListEventsResponse) String() string { return "ListEventsResponse" }
func (m *ListEventsResponse) ProtoMessage()  {}

// Empty is an empty proto message.
type Empty struct{}

func (m *Empty) Reset()        { *m = Empty{} }
func (m *Empty) String() string { return "Empty" }
func (m *Empty) ProtoMessage()  {}
