version: "2"

run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocritic
    - bodyclose
    - nilerr

issues:
  exclude-dirs:
    - pkg/api
