// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: faq_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFAQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	Category      *string                `protobuf:"bytes,3,opt,name=category,proto3,oneof" json:"category,omitempty"`
	SortOrder     *int32                 `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFAQRequest) Reset() {
	*x = CreateFAQRequest{}
	mi := &file_faq_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFAQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFAQRequest) ProtoMessage() {}

func (x *CreateFAQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faq_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFAQRequest.ProtoReflect.Descriptor instead.
func (*CreateFAQRequest) Descriptor() ([]byte, []int) {
	return file_faq_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFAQRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *CreateFAQRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *CreateFAQRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *CreateFAQRequest) GetSortOrder() int32 {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return 0
}

type GetFAQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFAQRequest) Reset() {
	*x = GetFAQRequest{}
	mi := &file_faq_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFAQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFAQRequest) ProtoMessage() {}

func (x *GetFAQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faq_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFAQRequest.ProtoReflect.Descriptor instead.
func (*GetFAQRequest) Descriptor() ([]byte, []int) {
	return file_faq_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetFAQRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateFAQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Question      *string                `protobuf:"bytes,2,opt,name=question,proto3,oneof" json:"question,omitempty"`
	Answer        *string                `protobuf:"bytes,3,opt,name=answer,proto3,oneof" json:"answer,omitempty"`
	Category      *string                `protobuf:"bytes,4,opt,name=category,proto3,oneof" json:"category,omitempty"`
	SortOrder     *int32                 `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFAQRequest) Reset() {
	*x = UpdateFAQRequest{}
	mi := &file_faq_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFAQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFAQRequest) ProtoMessage() {}

func (x *UpdateFAQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faq_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFAQRequest.ProtoReflect.Descriptor instead.
func (*UpdateFAQRequest) Descriptor() ([]byte, []int) {
	return file_faq_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateFAQRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFAQRequest) GetQuestion() string {
	if x != nil && x.Question != nil {
		return *x.Question
	}
	return ""
}

func (x *UpdateFAQRequest) GetAnswer() string {
	if x != nil && x.Answer != nil {
		return *x.Answer
	}
	return ""
}

func (x *UpdateFAQRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *UpdateFAQRequest) GetSortOrder() int32 {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return 0
}

type DeleteFAQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFAQRequest) Reset() {
	*x = DeleteFAQRequest{}
	mi := &file_faq_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFAQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFAQRequest) ProtoMessage() {}

func (x *DeleteFAQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faq_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFAQRequest.ProtoReflect.Descriptor instead.
func (*DeleteFAQRequest) Descriptor() ([]byte, []int) {
	return file_faq_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteFAQRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListFAQsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *string                `protobuf:"bytes,1,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Page          *int32                 `protobuf:"varint,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageSize      *int32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFAQsRequest) Reset() {
	*x = ListFAQsRequest{}
	mi := &file_faq_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFAQsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFAQsRequest) ProtoMessage() {}

func (x *ListFAQsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faq_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFAQsRequest.ProtoReflect.Descriptor instead.
func (*ListFAQsRequest) Descriptor() ([]byte, []int) {
	return file_faq_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListFAQsRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *ListFAQsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListFAQsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

type FAQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	Category      *string                `protobuf:"bytes,4,opt,name=category,proto3,oneof" json:"category,omitempty"`
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EditedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=edited_at,json=editedAt,proto3" json:"edited_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FAQ) Reset() {
	*x = FAQ{}
	mi := &file_faq_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FAQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FAQ) ProtoMessage() {}

func (x *FAQ) ProtoReflect() protoreflect.Message {
	mi := &file_faq_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FAQ.ProtoReflect.Descriptor instead.
func (*FAQ) Descriptor() ([]byte, []int) {
	return file_faq_service_proto_rawDescGZIP(), []int{5}
}

func (x *FAQ) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FAQ) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *FAQ) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *FAQ) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *FAQ) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *FAQ) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FAQ) GetEditedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EditedAt
	}
	return nil
}

type ListFAQsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Faqs          []*FAQ                 `protobuf:"bytes,1,rep,name=faqs,proto3" json:"faqs,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFAQsResponse) Reset() {
	*x = ListFAQsResponse{}
	mi := &file_faq_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFAQsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFAQsResponse) ProtoMessage() {}

func (x *ListFAQsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_faq_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFAQsResponse.ProtoReflect.Descriptor instead.
func (*ListFAQsResponse) Descriptor() ([]byte, []int) {
	return file_faq_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListFAQsResponse) GetFaqs() []*FAQ {
	if x != nil {
		return x.Faqs
	}
	return nil
}

func (x *ListFAQsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFAQsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []string               `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_faq_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_faq_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_faq_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListCategoriesResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_faq_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_faq_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_faq_service_proto_rawDescGZIP(), []int{8}
}

var File_faq_service_proto protoreflect.FileDescriptor

const file_faq_service_proto_rawDesc = "" +
	"\n" +
	"\x11faq_service.proto\x12\x06faq.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x01\n" +
	"\x10CreateFAQRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12\x1f\n" +
	"\bcategory\x18\x03 \x01(\tH\x00R\bcategory\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05H\x01R\tsortOrder\x88\x01\x01B\v\n" +
	"\t_categoryB\r\n" +
	"\v_sort_order\"\x1f\n" +
	"\rGetFAQRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd9\x01\n" +
	"\x10UpdateFAQRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\bquestion\x18\x02 \x01(\tH\x00R\bquestion\x88\x01\x01\x12\x1b\n" +
	"\x06answer\x18\x03 \x01(\tH\x01R\x06answer\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x04 \x01(\tH\x02R\bcategory\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05H\x03R\tsortOrder\x88\x01\x01B\v\n" +
	"\t_questionB\t\n" +
	"\a_answerB\v\n" +
	"\t_categoryB\r\n" +
	"\v_sort_order\"\"\n" +
	"\x10DeleteFAQRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x91\x01\n" +
	"\x0fListFAQsRequest\x12\x1f\n" +
	"\bcategory\x18\x01 \x01(\tH\x00R\bcategory\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x02 \x01(\x05H\x01R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x03 \x01(\x05H\x02R\bpageSize\x88\x01\x01B\v\n" +
	"\t_categoryB\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_size\"\x8a\x02\n" +
	"\x03FAQ\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer\x12\x1f\n" +
	"\bcategory\x18\x04 \x01(\tH\x00R\bcategory\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tedited_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\beditedAtB\v\n" +
	"\t_category\"h\n" +
	"\x10ListFAQsResponse\x12\x1f\n" +
	"\x04faqs\x18\x01 \x03(\v2\v.faq.v1.FAQR\x04faqs\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\"8\n" +
	"\x16ListCategoriesResponse\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories\"\a\n" +
	"\x05Empty2\xd8\x02\n" +
	"\n" +
	"FAQService\x122\n" +
	"\tCreateFAQ\x12\x18.faq.v1.CreateFAQRequest\x1a\v.faq.v1.FAQ\x12,\n" +
	"\x06GetFAQ\x12\x15.faq.v1.GetFAQRequest\x1a\v.faq.v1.FAQ\x122\n" +
	"\tUpdateFAQ\x12\x18.faq.v1.UpdateFAQRequest\x1a\v.faq.v1.FAQ\x124\n" +
	"\tDeleteFAQ\x12\x18.faq.v1.DeleteFAQRequest\x1a\r.faq.v1.Empty\x12=\n" +
	"\bListFAQs\x12\x17.faq.v1.ListFAQsRequest\x1a\x18.faq.v1.ListFAQsResponse\x12?\n" +
	"\x0eListCategories\x12\r.faq.v1.Empty\x1a\x1e.faq.v1.ListCategoriesResponseB\vZ\t./pkg/apib\x06proto3"

var (
	file_faq_service_proto_rawDescOnce sync.Once
	file_faq_service_proto_rawDescData []byte
)

func file_faq_service_proto_rawDescGZIP() []byte {
	file_faq_service_proto_rawDescOnce.Do(func() {
		file_faq_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_faq_service_proto_rawDesc), len(file_faq_service_proto_rawDesc)))
	})
	return file_faq_service_proto_rawDescData
}

var file_faq_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_faq_service_proto_goTypes = []any{
	(*CreateFAQRequest)(nil),       // 0: faq.v1.CreateFAQRequest
	(*GetFAQRequest)(nil),          // 1: faq.v1.GetFAQRequest
	(*UpdateFAQRequest)(nil),       // 2: faq.v1.UpdateFAQRequest
	(*DeleteFAQRequest)(nil),       // 3: faq.v1.DeleteFAQRequest
	(*ListFAQsRequest)(nil),        // 4: faq.v1.ListFAQsRequest
	(*FAQ)(nil),                    // 5: faq.v1.FAQ
	(*ListFAQsResponse)(nil),       // 6: faq.v1.ListFAQsResponse
	(*ListCategoriesResponse)(nil), // 7: faq.v1.ListCategoriesResponse
	(*Empty)(nil),                  // 8: faq.v1.Empty
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
}
var file_faq_service_proto_depIdxs = []int32{
	9, // 0: faq.v1.FAQ.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: faq.v1.FAQ.edited_at:type_name -> google.protobuf.Timestamp
	5, // 2: faq.v1.ListFAQsResponse.faqs:type_name -> faq.v1.FAQ
	0, // 3: faq.v1.FAQService.CreateFAQ:input_type -> faq.v1.CreateFAQRequest
	1, // 4: faq.v1.FAQService.GetFAQ:input_type -> faq.v1.GetFAQRequest
	2, // 5: faq.v1.FAQService.UpdateFAQ:input_type -> faq.v1.UpdateFAQRequest
	3, // 6: faq.v1.FAQService.DeleteFAQ:input_type -> faq.v1.DeleteFAQRequest
	4, // 7: faq.v1.FAQService.ListFAQs:input_type -> faq.v1.ListFAQsRequest
	8, // 8: faq.v1.FAQService.ListCategories:input_type -> faq.v1.Empty
	5, // 9: faq.v1.FAQService.CreateFAQ:output_type -> faq.v1.FAQ
	5, // 10: faq.v1.FAQService.GetFAQ:output_type -> faq.v1.FAQ
	5, // 11: faq.v1.FAQService.UpdateFAQ:output_type -> faq.v1.FAQ
	8, // 12: faq.v1.FAQService.DeleteFAQ:output_type -> faq.v1.Empty
	6, // 13: faq.v1.FAQService.ListFAQs:output_type -> faq.v1.ListFAQsResponse
	7, // 14: faq.v1.FAQService.ListCategories:output_type -> faq.v1.ListCategoriesResponse
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_faq_service_proto_init() }
func file_faq_service_proto_init() {
	if File_faq_service_proto != nil {
		return
	}
	file_faq_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_faq_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_faq_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_faq_service_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_faq_service_proto_rawDesc), len(file_faq_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_faq_service_proto_goTypes,
		DependencyIndexes: file_faq_service_proto_depIdxs,
		MessageInfos:      file_faq_service_proto_msgTypes,
	}.Build()
	File_faq_service_proto = out.File
	file_faq_service_proto_goTypes = nil
	file_faq_service_proto_depIdxs = nil
}
