// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.1
// source: faq_service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FAQService_CreateFAQ_FullMethodName      = "/faq_service.v1.FAQService/CreateFAQ"
	FAQService_GetFAQ_FullMethodName         = "/faq_service.v1.FAQService/GetFAQ"
	FAQService_UpdateFAQ_FullMethodName      = "/faq_service.v1.FAQService/UpdateFAQ"
	FAQService_DeleteFAQ_FullMethodName      = "/faq_service.v1.FAQService/DeleteFAQ"
	FAQService_ListFAQs_FullMethodName       = "/faq_service.v1.FAQService/ListFAQs"
	FAQService_ListCategories_FullMethodName = "/faq_service.v1.FAQService/ListCategories"
)

// FAQServiceClient is the client API for FAQService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FAQServiceClient interface {
	CreateFAQ(ctx context.Context, in *CreateFAQRequest, opts ...grpc.CallOption) (*FAQ, error)
	GetFAQ(ctx context.Context, in *GetFAQRequest, opts ...grpc.CallOption) (*FAQ, error)
	UpdateFAQ(ctx context.Context, in *UpdateFAQRequest, opts ...grpc.CallOption) (*FAQ, error)
	DeleteFAQ(ctx context.Context, in *DeleteFAQRequest, opts ...grpc.CallOption) (*Empty, error)
	ListFAQs(ctx context.Context, in *ListFAQsRequest, opts ...grpc.CallOption) (*ListFAQsResponse, error)
	ListCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
}

type fAQServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFAQServiceClient(cc grpc.ClientConnInterface) FAQServiceClient {
	return &fAQServiceClient{cc}
}

func (c *fAQServiceClient) CreateFAQ(ctx context.Context, in *CreateFAQRequest, opts ...grpc.CallOption) (*FAQ, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FAQ)
	err := c.cc.Invoke(ctx, FAQService_CreateFAQ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fAQServiceClient) GetFAQ(ctx context.Context, in *GetFAQRequest, opts ...grpc.CallOption) (*FAQ, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FAQ)
	err := c.cc.Invoke(ctx, FAQService_GetFAQ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fAQServiceClient) UpdateFAQ(ctx context.Context, in *UpdateFAQRequest, opts ...grpc.CallOption) (*FAQ, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FAQ)
	err := c.cc.Invoke(ctx, FAQService_UpdateFAQ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fAQServiceClient) DeleteFAQ(ctx context.Context, in *DeleteFAQRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, FAQService_DeleteFAQ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fAQServiceClient) ListFAQs(ctx context.Context, in *ListFAQsRequest, opts ...grpc.CallOption) (*ListFAQsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFAQsResponse)
	err := c.cc.Invoke(ctx, FAQService_ListFAQs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fAQServiceClient) ListCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCategoriesResponse)
	err := c.cc.Invoke(ctx, FAQService_ListCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FAQServiceServer is the server API for FAQService service.
// All implementations must embed UnimplementedFAQServiceServer
// for forward compatibility.
type FAQServiceServer interface {
	CreateFAQ(context.Context, *CreateFAQRequest) (*FAQ, error)
	GetFAQ(context.Context, *GetFAQRequest) (*FAQ, error)
	UpdateFAQ(context.Context, *UpdateFAQRequest) (*FAQ, error)
	DeleteFAQ(context.Context, *DeleteFAQRequest) (*Empty, error)
	ListFAQs(context.Context, *ListFAQsRequest) (*ListFAQsResponse, error)
	ListCategories(context.Context, *Empty) (*ListCategoriesResponse, error)
	mustEmbedUnimplementedFAQServiceServer()
}

// UnimplementedFAQServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFAQServiceServer struct{}

func (UnimplementedFAQServiceServer) CreateFAQ(context.Context, *CreateFAQRequest) (*FAQ, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFAQ not implemented")
}
func (UnimplementedFAQServiceServer) GetFAQ(context.Context, *GetFAQRequest) (*FAQ, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFAQ not implemented")
}
func (UnimplementedFAQServiceServer) UpdateFAQ(context.Context, *UpdateFAQRequest) (*FAQ, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFAQ not implemented")
}
func (UnimplementedFAQServiceServer) DeleteFAQ(context.Context, *DeleteFAQRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFAQ not implemented")
}
func (UnimplementedFAQServiceServer) ListFAQs(context.Context, *ListFAQsRequest) (*ListFAQsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFAQs not implemented")
}
func (UnimplementedFAQServiceServer) ListCategories(context.Context, *Empty) (*ListCategoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCategories not implemented")
}
func (UnimplementedFAQServiceServer) mustEmbedUnimplementedFAQServiceServer() {}
func (UnimplementedFAQServiceServer) testEmbeddedByValue()                    {}

// UnsafeFAQServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FAQServiceServer will
// result in compilation errors.
type UnsafeFAQServiceServer interface {
	mustEmbedUnimplementedFAQServiceServer()
}

func RegisterFAQServiceServer(s grpc.ServiceRegistrar, srv FAQServiceServer) {
	// If the following call panics, it indicates UnimplementedFAQServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FAQService_ServiceDesc, srv)
}

func _FAQService_CreateFAQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFAQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FAQServiceServer).CreateFAQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FAQService_CreateFAQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FAQServiceServer).CreateFAQ(ctx, req.(*CreateFAQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FAQService_GetFAQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFAQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FAQServiceServer).GetFAQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FAQService_GetFAQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FAQServiceServer).GetFAQ(ctx, req.(*GetFAQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FAQService_UpdateFAQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFAQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FAQServiceServer).UpdateFAQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FAQService_UpdateFAQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FAQServiceServer).UpdateFAQ(ctx, req.(*UpdateFAQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FAQService_DeleteFAQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFAQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FAQServiceServer).DeleteFAQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FAQService_DeleteFAQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FAQServiceServer).DeleteFAQ(ctx, req.(*DeleteFAQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FAQService_ListFAQs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFAQsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FAQServiceServer).ListFAQs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FAQService_ListFAQs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FAQServiceServer).ListFAQs(ctx, req.(*ListFAQsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FAQService_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FAQServiceServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FAQService_ListCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FAQServiceServer).ListCategories(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// FAQService_ServiceDesc is the grpc.ServiceDesc for FAQService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FAQService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "faq_service.v1.FAQService",
	HandlerType: (*FAQServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFAQ",
			Handler:    _FAQService_CreateFAQ_Handler,
		},
		{
			MethodName: "GetFAQ",
			Handler:    _FAQService_GetFAQ_Handler,
		},
		{
			MethodName: "UpdateFAQ",
			Handler:    _FAQService_UpdateFAQ_Handler,
		},
		{
			MethodName: "DeleteFAQ",
			Handler:    _FAQService_DeleteFAQ_Handler,
		},
		{
			MethodName: "ListFAQs",
			Handler:    _FAQService_ListFAQs_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _FAQService_ListCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "faq_service.proto",
}
